run:
  deadline: 60m

linters:
  enable-all: true
  disable: maligned,golint,scopelint,interfacer,ireturn,wrapcheck,forbidigo,varnamelen

output:
  format: colored-line-number

linters-settings:
  dupl:
    # tokens count to trigger issue, 150 by default
    threshold: 200
  nestif:
    # their are various nested if else, therefore specifying complexity as 26
    min-complexity: 26
