on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

name: lint
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Run lint
        timeout-minutes: 30
        run: |
          cd $GITHUB_WORKSPACE && make lint